$schema: "http://json-schema.org/draft-04/schema#"

description: snakemake configuration file

type: object

properties:
  samples:
    type: string
  units:
    type: string

  ref:
    type: object
    properties:
      species:
        type: string
      build:
        type: string
      release:
        type: integer
    required:
      - species
      - build
      - release

  filtering:
    type: object
    properties:
      vqsr:
        type: boolean
      hard:
        type: object
        properties:
          snvs:
            type: string
          indels:
            type: string
        required:
          - snvs
          - indels
    required:
      - vqsr
      - hard

  processing:
    type: object
    properties:
      remove-duplicates:
        type: boolean
      restrict-regions:
        type: string
      region-padding:
        type: integer
    required:
      - remove-duplicates

  params:
    type: object
    properties:
      gatk:
        type: object
        properties:
          HaplotypeCaller:
            type: string
          BaseRecalibrator:
            type: string
          GenotypeGVCFs:
            type: string
          VariantRecalibrator:
            type: string
        required:
          - HaplotypeCaller
          - BaseRecalibrator
          - GenotypeGVCFs
          - VariantRecalibrator
      picard:
        type: object
        properties:
          MarkDuplicates:
            type: string
        required:
          - MarkDuplicates
    required:
      - gatk
      - picard

required:
  - samples
  - units
  - ref
  - filtering
  - processing
  - params
